apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobify-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobify-back
  template:
    metadata:
      labels:
        app: jobify-back
    spec:
      containers:
        - name: jobify-back
          image: gucasassi/jobify-back:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: jobify-back-config
                  key: app_port

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: jobify-back-secret
                  key: mongodb_uri
